version: '3'

services:
  app:
    build:
      dockerfile: .LuizaLabs.Api/dockerfile
      context: .
    container_name: app
    ports:
      - "80:80"
    depends_on: 
      - "db-postgres"
    environment:
      POSTGRE_CONNECTIONSTRING: Host=db-postgres;Port=5432;Database=postgres;User ID=postgres;Password=postgres      
    networks: 
      - default_network
  db-postgres:
    image: postgres
    container_name: db-postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks: 
      - default_network   
networks: 
  default_network:
    driver: bridge